apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: kube-system
  name: cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cloud-controller-manager
  apiGroup: rbac.authorization.k8s.io
